# https://github.com/elastic/beats/blob/master/filebeat/filebeat.reference.yml
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml # enable all modules (nginx, kafka, redis, etc)
    reload.enabled: false

#========================== Filebeat autodiscover ==============================
filebeat.autodiscover:
  providers:
    - type: docker
      # hints.enabled: true
      hints.default_config.enabled: false
      templates:
        - condition.equals.docker.container.labels.logging/enabled: "true"
          config:
            - type: container
              format: docker
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
              json:
                # keys_under_root: true
                # message_key: json
                # overwrite_keys: true
                add_error_key: true
                expand_keys: true
                ignore_decoding_error: true

#================================ Processors ===================================
processors:
  - add_docker_metadata: {}
  - add_locale:
      format: offset
  - add_host_metadata:
      netinfo.enabled: true
  - drop_event:
      when:
        contains:
          json.error.message: "Error decoding JSON"

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: elastic
  password: elastic

#============================== Dashboards =====================================
setup.dashboards:
  enabled: true

#============================== Kibana =========================================
setup.kibana:
  host: "http://kibana:5601"
  username: elastic
  password: elastic

#============================== Xpack Monitoring ===============================
xpack.monitoring:
  enabled: false
  elasticsearch:

monitoring.enabled: false
