heartbeat.monitors:
  - type: http
    id: identity-service
    tags: ["identity", "service"]
    name: Identity Service
    schedule: "@every 10s"
    hosts: ["http://host.docker.internal:1000/api/healthz"]
    check.response:
      status: [200]
      body:
        - Healthy

  - type: http
    id: user-service
    tags: ["user", "service"]
    name: User Service
    schedule: "@every 10s"
    hosts: ["http://host.docker.internal:1001/api/healthz"]
    check.response:
      status: [200]
      body:
        - Healthy

  - type: http
    id: catalog-service
    tags: ["catalog", "service"]
    name: Catalog Service
    schedule: "@every 10s"
    hosts: ["http://host.docker.internal:1002/api/healthz"]
    check.response:
      status: [200]
      body:
        - Healthy

  - type: http
    id: basket-service
    tags: ["basket", "service"]
    name: Basket Service
    schedule: "@every 10s"
    hosts: ["http://host.docker.internal:1003/api/healthz"]
    check.response:
      status: [200]
      body:
        - Healthy

  - type: http
    id: order-service
    tags: ["order", "service"]
    name: Order Service
    schedule: "@every 10s"
    hosts: ["http://host.docker.internal:1004/api/healthz"]
    check.response:
      status: [200]
      body:
        - Healthy

  - type: http
    id: email-service
    tags: ["email", "service"]
    name: Email Service
    schedule: "@every 10s"
    hosts: ["http://host.docker.internal:1005/api/healthz"]
    check.response:
      status: [200]
      body:
        - Healthy

  - type: http
    id: login-ui
    tags: ["login", "ui"]
    name: Login UI
    schedule: "@every 10s"
    urls: "http://host.docker.internal:2000"
    check.response:
      status: [200]

  - type: http
    id: shop-ui
    tags: ["shop", "ui"]
    name: Shop UI
    schedule: "@every 10s"
    urls: "http://host.docker.internal:2001"
    check.response:
      status: [200]

  - type: http
    id: internal-ui
    tags: ["internal", "ui"]
    name: Internal UI
    schedule: "@every 10s"
    urls: "http://host.docker.internal:2002"
    check.response:
      status: [200]

processors:
  - add_docker_metadata: ~

monitoring.enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: elastic
  password: elastic

logging.to_files: false
